// Code generated by goctl. DO NOT EDIT.
package types

type BaseResp struct {
	Ok bool `json:"ok"`
}

type Domain struct {
	Name string `path:"name"`
}

type Zone struct {
	Domain  string   `json:"domain"`
	Serial  int64    `json:"serial"`
	Records []Record `json:"records"`
}

type Record struct {
	RecordType  string `json:"record_type"`
	Host        string `json:"host,optional"`
	PointsTo    string `json:"points_to,optional"`
	Ttl         int64  `json:"ttl"`
	MxPriority  int64  `json:"mx_priority,optional"`
	SrvService  string `json:"srv_service,optional"`
	SrvProtocol string `json:"srv_protocol,optional"`
	SrvName     string `json:"srv_name,optional"`
	SrvTarget   string `json:"srv_target,optional"`
	SrvPriority int64  `json:"srv_priority,optional"`
	SrvWeight   int64  `json:"srv_weight,optional"`
	SrvPort     int64  `json:"srv_port,optional"`
	CaaName     string `json:"caa_name,optional"`
	CaaFlags    string `json:"caa_flags,optional"`
	CaaTag      string `json:"caa_tag,optional"`
	CaaValue    string `json:"caa_value,optional"`
}
