// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mydns/master/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Author},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/domain",
					Handler: DomainAddHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/domain/:name",
					Handler: DomainDelHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/record",
					Handler: RecordAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/record",
					Handler: RecordEditHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/record",
					Handler: RecordDelHandler(serverCtx),
				},
			}...,
		),
	)
}
